[package]
name = "build_run"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.5.0"
cargo_toml = "0.19.2"
clap = { version = "4.5.4", features = ["cargo", "derive"] }
env_logger = "0.11.3"
log = "0.4.21"
regex = "1.10.3"
serde = { version = "1.0.98", features = ["derive"] }
toml = "0.8.12"
crossterm = "0.27.0"
ratatui = "0.26.2"
tui-textarea = { version = "0.4.0", features = ["crossterm", "search"] }
clap-repl = "0.1.1"
console = "0.15.8"
rustyline = { version = "14.0.0", features = [
    "with-file-history",
    "default",
    "derive",
] }
syn = { version = "2.0.60", features = ["full"] }
quote = "1.0.36"
strum = { version = "0.26.2", features = ["derive"] }
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
lazy_static = "1.4.0"
homedir = "0.2.1"
edit = "0.1.5"
termbg = "0.5.0"
