[package]
name = "build_run"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.5.0"
clap = { version = "4.5.4", features = ["cargo", "derive"] }
env_logger = "0.11.3"
log = "0.4.21"
regex = "1.10.3"
serde = { version = "1.0.98", features = ["derive"] }
toml = "0.8.12"
crossterm = "0.27.0"
syn = { version = "2.0.60", features = ["extra-traits", "full", "visit"] }
quote = "1.0.36"
strum = { version = "0.26.2", features = ["derive", "phf"] }
lazy_static = "1.4.0"
homedir = "0.2.1"
edit = "0.1.5"
termbg = "0.5.0"
supports-color = "3.0.0"
reedline = "0.32.0"
nu-ansi-term = "0.50.0"
reedline-repl-rs = "1.1.1"
wsl = "0.1.0"

[profile.dev]
opt-level = 1 # Use slightly better optimizations.
