
  [package]
  name = "my_generated_program"
  version = "0.0.1"

  [dependencies]
  # Add any dependencies here

  [[bin]]
  name = "my_generated_program"
  path = "/Users/donf/projects/build_run/.cargo/build_run/source.rs"
  