edition = "2021"

[package]
name = "factorial_main_ok"
version = "0.1.0"

[workspace]

[[bin]]
path = "/Users/donf/projects/build_run/.cargo/build_run/factorial_main_ok.rs"
name = "factorial_main_ok"
