
  [package]
  name = "build_run_demo"
  version = "0.0.1"

  [dependencies]
  # Add any dependencies here

  [[bin]]
  name = "build_run_demo"
  path = "/Users/donf/projects/build_run/.cargo/build_run/tmp_source.rs"
  